config/routes.rb
Rails.application.routes.draw do
  resources :occurrency_histories
  resources :emotions
  devise_for :readers, path: 'reader', controllers: {
    sessions: 'readers/sessions',
    registrations: 'readers/registrations',
    passwords: 'readers/passwords'
  }

  devise_for :users, path: '', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :reader do
    root to: "books#list"
    resources :guests
    resources :readers
    resources :books

    patch "/reader/update_book_comments/:id", to: "readers#update_book_comments", as: :edit_book_comment
    delete "/reader/update_book_comments/:id", to: "readers#delete_book_comments", as: :delete_book_comment
    post "/livros/add/:code", to: "readers#add_book", as: :add_book
    get "/validate_book_code", to: "readers#validate_book_code", as: :validate_book_code
  end

  authenticated :user do
    root to: "application#dashboard"

    resources :appointments do
      get :autocomplete_student_name, :on => :collection
      get :autocomplete_guest_name, :on => :collection
    end
    resources :occurrencies do
      get :autocomplete_student_name, :on => :collection
    end

    resources :appointment_evolutions
    resources :students
    resources :users
    resources :schools
    resources :phrases
    resources :guests, except: [:show]
    resources :classies
    resources :readers
    resources :books

    get "/review_occurrency/:occurrency_id", to: "application#review_occurrency", as: :review_occurrency
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "application#coming_soon"

  # Static pages of the application
  get "slides", to: "application#slides", as: :slide_show
  get "about", to: "application#about", as: :about_page
  get "soon", to: "application#soon", as: :soon

  # guests personalized routes
  post "/guests/generate_access_cards", to: "guests#generate_access_cards", as: :generate_access_cards
  get "/guests/print_access_cards", to: "guests#print_access_cards", as: :print_access_cards

  # book personalized routes
  get "/livro/:url", to: "books#read", as: :read_book
  get "/livros", to: "books#list", as: :books_list

  post "/students/:id/add_document", to: "students#add_document", as: :add_document
  post "/update_book_page_saver", to: "books#update_current_page"

  # Relatories routes
  get "/relatories", to: "relatories#index", as: :relatories
  get "/relatories/appointments", to: "relatories#appointments", as: :appointments_relatory
  get "/relatories/occurrencies", to: "relatories#occurrencies", as: :occurrencies_relatory
  get "/relatories/print_appointments/:ids", to: "relatories#print_appointments", as: :print_appointments_relatory
  get "/relatories/print_occurrencies/:ids", to: "relatories#print_occurrencies", as: :print_occurrencies_relatory
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school
  has_many :occurrency_students, dependent: :destroy
  has_many :appointment_students, dependent: :destroy
  has_many :student_documents, dependent: :destroy
  has_many :occurrency_histories, dependent: :destroy

  accepts_nested_attributes_for :student_documents, allow_destroy: true, reject_if: :all_blank

  # has_trash
  validates_presence_of :name, :school, :classy, :groupy

  self.per_page = 10

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_school_id
    ]
  )

  scope :search_query, lambda { |query| where("name LIKE ? OR classy LIKE ? OR groupy LIKE ?", "%#{query}%","%#{query}%","%#{query}%") }
  scope :with_school_id, lambda { |school_id| where(:school_id => school_id) }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'

    case sort_option.to_s
    when /^name/
      order("LOWER(students.name) #{ direction }")
    when /^classy/
      order("LOWER(students.classy) #{ direction }")
    when /^group/
      order("LOWER(students.groupy) #{ direction }")
    when /^created_at/
      order("LOWER(students.created_at) #{ direction }")
    else
      raise(ArgumentError, "Opção inválida: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Nome (a-z)', 'name_asc'],
      ['Nome (z-a)', 'name_desc'],
      ['Ano (a-z)', 'classy_asc'],
      ['Ano (z-a)', 'classy_desc'],
      ['Turma (a-z)', 'groupy_asc'],
      ['Turma (z-a)', 'groupy_desc'],
      ['Data de Registro (novos primeiro)', 'created_at_desc'],
      ['Data de Registro (antigos primeiro)', 'created_at_asc']
    ]
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :add_document]
  before_action :authenticate_user!

  layout "users"

  # GET /students
  # GET /students.json
  def index
    @filterrific = initialize_filterrific(
      Student,
      params[:filterrific],
      select_options: {
        with_school_id: School.all.collect {|a| [a.name, a.id]},
        sorted_by: Student.options_for_sorted_by
      }
    ) or return
    @students = @filterrific.find.page(params[:page]) if is_admin?
    @students = @filterrific.find.where(:school_id => current_user.school_id).page(params[:page]) if not is_admin?

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @student.student_documents.build
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if is_admin? || student_params[:school_id].to_s == current_user.school_id.to_s
        if @student.save
          format.html { redirect_to @student, flash: {:success => 'Estudante criado'} }
          format.json { render :show, status: :created, location: @student }
        else
          format.html { render :new }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if is_admin? || student_params[:school_id].to_s == current_user.school_id.to_s
        if @student.update(student_params)
          format.html { redirect_to @student, flash: {:success => 'Estudante atualizado'} }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { render :edit }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, flash: {:info => 'Estudante Excluído'} }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /students/1/add_document
  def add_document
    respond_to do |format|
      if is_admin? || student_params[:school_id].to_s == current_user.school_id.to_s
        if @student.update(student_params)
          format.html { redirect_to @student, flash: {:success => 'Estudante atualizado'} }
          format.json { render :show, status: :ok, location: @student }
        else
          format.html { redirect_to @student, flash: {:danger => 'Todos os campos precisam ser preenchidos corretamente, verifique se o tipo do arquivo enviado corresponde com os tipos de arquivos permitidos'} }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :school_id, :classy, :groupy, :student_documents_attributes => [:name, :id, :_destroy, :file, :student_id])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@student, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form" }) do |f|
  %strong= f.error_notification
  %p= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  %br

  - if is_admin?
    = f.input :school_id, label: "Escola", as: :select, collection: School.all.drop(1), input_html: { class: "fancy-form__input fancy-form__select" }
  - else
    = f.input :school_id, label: "Escola", as: :hidden, input_html: { value: School.find_by_id(current_user.school.id).id }

  = f.input :name, label: "Nome"
  = f.input :classy, label: "Ano/Série", as: :select, collection: Classy.all.collect {|p| [ p.name, p.name ] }
  = f.input :groupy, label: "Turma"

  = f.submit "Salvar", class: "button button--green fancy-link--white"

app/views/students/_list.html.haml
#filterrific_results
  %br
  %br

  - if not @students.empty?
    .table
      %table.table
        %thead
          %tr
            %th{style: "width: 20px"}
            %th Escola
            %th Nome
            %th Ano
            %th Turma
            %th
            %th
        %tbody
          - @students.each do |student|
            %tr
              %td
                %div{style: "background-color: #{student.school.color}; width: 20px; height: 20px;"}
              %td= student.school.name
              %td= student.name
              %td= student.classy
              %td= student.groupy
              %td{style: "text-align: center"}= link_to icon('fas', 'eye', 'Ver', class: "fancy-link fancy-link--blue2"), student, class: "fancy-link fancy-link--blue2"
              %td= link_to icon('fas', 'pen', 'Editar', class: "fancy-link fancy-link--green"), edit_student_path(student), class: "fancy-link fancy-link--green"
              %td= link_to icon('fas', 'trash', 'Excluir', class: "fancy-link fancy-link--red"), student, method: :delete, data: { confirm: 'Are you sure?' }, class: "fancy-link fancy-link--red"

  - else
    = image_tag('brain.png', class: "logo-default logo-default--small")
    %h1.title.title--grey Não há nada disso por aqui...


  %br
  = will_paginate students # provided by will_paginate

app/views/students/edit.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Editar Estudante

      %div
        = render 'form'

app/views/students/index.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Estudantes

      %br

      = form_for_filterrific @filterrific, html: { class: "fancy-form fancy-form--inline" } do |f|
        %div
          Buscar por palavra chave
          = f.text_field(                                |
              :search_query,                             |
              class: 'filterrific-periodically-observed fancy-form__input', |
              placeholder: 'Nome, Ano, Turma...' |
            )                                            |

        - if is_admin?
          %div
            Escola
            \#{f.select( :with_school_id, @filterrific.select_options[:with_school_id], { include_blank: 'Todas' }, class: "fancy-form__input fancy-form__select" )}
        %div
          Organizar por
          = f.select( :sorted_by, @filterrific.select_options[:sorted_by] )
        %div
          = link_to(                 |
              'Resetar',       |
              reset_filterrific_url, |
              class: "fancy-link fancy-link--blue2" |
            )                        |

        = f.submit 'Filtrar', class: "button button--green fancy-link--white"

      = render(                           |
          partial: 'students/list',       |
          locals: { students: @students } |
        )                                 |

      %br

      = link_to '+ Adicionar Estudante', new_student_path, class: "fancy-link fancy-link--blue2"

app/views/students/index.js.haml
- js = escape_javascript(
- render(partial: 'students/list', locals: { students: @students })
- )
$("#filterrific_results").html("#{js}");

app/views/students/new.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Novo Estudante

      %div
        = render 'form'

app/views/students/show.html.haml
.animated.fadeIn
  .section
    .section__content
      .inline
        %h1.title.title--large= @student.name

      .inline
        %h3.subtitle.title--thin= @student.school.name.capitalize
        %h3.subtitle.title--thin{style: "margin-left: 30px"}= "Série/Turma: " + @student.classy + ' ' + @student.groupy

      = link_to 'Editar', edit_student_path(@student), class: "fancy-link fancy-link--blue2"

      %br
      %br

      - if @student.student_documents.any?
        %h2 Documentos e Arquivos

        .slider{style: "width: 100%; overflow: hidden"}
          .slider__content{style: "overflow-x:scroll; display: -webkit-inline-box; width: -webkit-fill-available;"}
            - @student.student_documents.each do |sd|
              .card.card--with-border{style: "width: 250px; text-align: left; position: relative"}
                %div{id: "sd_#{sd.id}_s"}
                  %strong= sd.name
                  %br
                  %br
                  %a.fancy-link.fancy-link--blue{href: "#{sd.file}", target: "_blank"}= icon('fas', 'eye', "Visualizar arquivo")

                %div{id: "sd_#{sd.id}_d", style: "display: none"}
                  = simple_form_for(@student, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form", id: "delete_attribute_#{sd.id}" }) do |f|
                    = f.simple_fields_for :student_documents, sd do |g|
                      = g.check_box '_destroy', checked: 'checked'

                %a.fancy-link.fancy-link--blue2{style: "position: absolute; right: 0; top: 0; cursor: pointer; margin: 10px", onclick: "if (confirm('Tem certeza que quer excluir esse comentário?')) { $('#delete_attribute_#{sd.id}').submit()};"}= icon('fas', 'trash', class: "fancy-link fancy-link--red")
        %br

      - if @student.appointment_students.any?
        %h2 Histórico de Atendimentos

        .slider{style: "width: 100%; overflow: hidden"}
          .slider__content{style: "overflow-x:scroll; display: -webkit-inline-box; width: -webkit-fill-available;"}
            - @student.appointment_students.each do |as|
              = link_to appointment_path(as.appointment), style: "color: unset; display: block; text-decoration: none;" do
                .card.card--with-border{style: "width: 250px; position: relative; padding-bottom: 30px"}
                  %strong= "ATENDIMENTO " + show_appointment_kind(as.appointment.kind)
                  %br
                  %br
                  %div{style: "text-align: left"}
                    = as.appointment.reason.first(100) + "..."
                    %br
                    %br
                  %div{style: "right: 10px; bottom: 10px; position: absolute"}
                    %em= l(as.appointment.appointment_date) + " às " + as.appointment.appointment_time

        %br

      - if @student.occurrency_students.any?
        %h2 Histórico de Ocorrências

        .slider{style: "width: 100%; overflow: hidden"}
          .slider__content{style: "overflow-x:scroll; display: -webkit-inline-box; width: -webkit-fill-available;"}
            - @student.occurrency_students.each do |os|
              = link_to occurrency_path(os.occurrency), style: "color: unset; display: block; text-decoration: none;" do
                .card.card--with-border{style: "width: 250px; position: relative; padding-bottom: 30px"}
                  %strong OCORRÊNCIA
                  %br
                  %br
                  %div{style: "text-align: left"}
                    = os.occurrency.description.first(100) + "..."
                    %br
                    %br
                  %div{style: "right: 10px; bottom: 10px; position: absolute"}
                    %em= os.occurrency.created_at.strftime("%d/%m/%Y - %H:%m")

        %br


      %div{style: "text-align: left"}
        %h3 Adicionar documento

        %br
        %br

        = simple_form_for @student, :url => add_document_path, :method => :post, defaults: { input_html: { class: "fancy-form__input" } } do |student|
          = student.simple_fields_for :student_documents, @student.student_documents.new do |f|
            = f.input :name, label: "Nome do documento"
            = f.input :file, label: "Arquivo (apenas arquivos em pdf, png, jpg ou jpeg)"
            %br
            = f.submit "Enviar", class: "button button--green fancy-link--white"