config/routes.rb
Rails.application.routes.draw do
  resources :occurrency_histories
  resources :emotions
  devise_for :readers, path: 'reader', controllers: {
    sessions: 'readers/sessions',
    registrations: 'readers/registrations',
    passwords: 'readers/passwords'
  }

  devise_for :users, path: '', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :reader do
    root to: "books#list"
    resources :guests
    resources :readers
    resources :books

    patch "/reader/update_book_comments/:id", to: "readers#update_book_comments", as: :edit_book_comment
    delete "/reader/update_book_comments/:id", to: "readers#delete_book_comments", as: :delete_book_comment
    post "/livros/add/:code", to: "readers#add_book", as: :add_book
    get "/validate_book_code", to: "readers#validate_book_code", as: :validate_book_code
  end

  authenticated :user do
    root to: "application#dashboard"

    resources :appointments do
      get :autocomplete_student_name, :on => :collection
      get :autocomplete_guest_name, :on => :collection
    end
    resources :occurrencies do
      get :autocomplete_student_name, :on => :collection
    end

    resources :appointment_evolutions
    resources :students
    resources :users
    resources :schools
    resources :phrases
    resources :guests, except: [:show]
    resources :classies
    resources :readers
    resources :books

    get "/review_occurrency/:occurrency_id", to: "application#review_occurrency", as: :review_occurrency
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "application#coming_soon"

  # Static pages of the application
  get "slides", to: "application#slides", as: :slide_show
  get "about", to: "application#about", as: :about_page
  get "soon", to: "application#soon", as: :soon

  # guests personalized routes
  post "/guests/generate_access_cards", to: "guests#generate_access_cards", as: :generate_access_cards
  get "/guests/print_access_cards", to: "guests#print_access_cards", as: :print_access_cards

  # book personalized routes
  get "/livro/:url", to: "books#read", as: :read_book
  get "/livros", to: "books#list", as: :books_list

  post "/students/:id/add_document", to: "students#add_document", as: :add_document
  post "/update_book_page_saver", to: "books#update_current_page"

  # Relatories routes
  get "/relatories", to: "relatories#index", as: :relatories
  get "/relatories/appointments", to: "relatories#appointments", as: :appointments_relatory
  get "/relatories/occurrencies", to: "relatories#occurrencies", as: :occurrencies_relatory
  get "/relatories/print_appointments/:ids", to: "relatories#print_appointments", as: :print_appointments_relatory
  get "/relatories/print_occurrencies/:ids", to: "relatories#print_occurrencies", as: :print_occurrencies_relatory
end

app/models/emotion.rb
class Emotion < ApplicationRecord
  has_many :feelings, dependent: :destroy

  accepts_nested_attributes_for :feelings, allow_destroy: true, reject_if: :all_blank
  validates_presence_of :name, :description
end

app/controllers/emotions_controller.rb
class EmotionsController < ApplicationController
  before_action :set_emotion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout "users"

  # GET /emotions
  # GET /emotions.json
  def index
    @emotions = Emotion.all
  end

  # GET /emotions/1
  # GET /emotions/1.json
  def show
  end

  # GET /emotions/new
  def new
    @emotion = Emotion.new
    @emotion.feelings.build
  end

  # GET /emotions/1/edit
  def edit
  end

  # POST /emotions
  # POST /emotions.json
  def create
    @emotion = Emotion.new(emotion_params)

    respond_to do |format|
      if @emotion.save
        format.html { redirect_to @emotion, notice: 'Emotion was successfully created.' }
        format.json { render :show, status: :created, location: @emotion }
      else
        format.html { render :new }
        format.json { render json: @emotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emotions/1
  # PATCH/PUT /emotions/1.json
  def update
    respond_to do |format|
      if @emotion.update(emotion_params)
        format.html { redirect_to @emotion, notice: 'Emotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @emotion }
      else
        format.html { render :edit }
        format.json { render json: @emotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emotions/1
  # DELETE /emotions/1.json
  def destroy
    @emotion.destroy
    respond_to do |format|
      format.html { redirect_to emotions_url, notice: 'Emotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emotion
      @emotion = Emotion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emotion_params
      params.require(:emotion).permit(:name, :description, feelings_attributes: [:description, :id, :_destroy])
    end
end

app/helpers/emotions_helper.rb
module EmotionsHelper
end

app/views/emotions/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@emotion, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form" }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name, label: "Nome da Emoção"
    = f.input :description, label: "Descrição (o que é, o que causa...)"

  %h3.subtitle.title--thin Sentimentos (Opções)
  = f.simple_fields_for :feelings do |g|
    = g.input :description, label: "Descrição do sentimento"

  .form-actions
    = f.submit "Salvar", class: "button button--green fancy-link--white"

app/views/emotions/edit.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Editando Emoção

      %div
        = render 'form'

app/views/emotions/index.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Emoções das ocorrências

      - if not @emotions.empty?
        %table.table
          %thead
            %tr
              %th Emoção
              %th
              %th
              %th

          %tbody
            - @emotions.each do |emotion|
              %tr
                %td= emotion.name
                %td= link_to icon('fas', 'eye', 'Ver', class: "fancy-link fancy-link--blue2"), emotion, class: "fancy-link fancy-link--blue2"
                %td= link_to icon('fas', 'pen', 'Editar', class: "fancy-link fancy-link--green"), edit_emotion_path(emotion), class: "fancy-link fancy-link--green"
                %td= link_to icon('fas', 'trash', 'Excluir', class: "fancy-link fancy-link--red"), emotion, method: :delete, data: { confirm: 'Tem certeza?' }, class: "fancy-link fancy-link--red"

      - else
        = image_tag('brain.png', class: "logo-default logo-default--small")
        %h1.title.title--grey Não há nada disso por aqui...

      %br

      = link_to '+ Adicionar', new_emotion_path, class: "fancy-link--blue2"

app/views/emotions/new.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Nova Emoção

      %div
        = render 'form'

app/views/emotions/show.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large= @emotion.name.capitalize

      .action
        %p= @emotion.description

        = link_to icon('fas', 'pen', ' Editar', class: "fancy-link fancy-link--blue2"), edit_emotion_path(@emotion), class: "fancy-link fancy-link--blue2"

      %h2.subtitle.title--thin Sentimentos

      %table.table
        %thead
          %tr
            %th Sentimento
            %th
            %th

        %tbody
          - @emotion.feelings.each do |feeling|
            %tr{id: "feeling_#{feeling.id}_s"}
              %td= feeling.description
              %td
                %a.fancy-link.fancy-link--green{style: "cursor: pointer", onclick: "$('#feeling_#{feeling.id}_s').toggle();$('#feeling_#{feeling.id}_e').toggle()"}= icon('fas', 'pen', 'Editar', class: "fancy-link fancy-link--green")
              %td
                %a.fancy-link.fancy-link--red{style: "cursor: pointer", onclick: "if (confirm('Tem certeza?')) { $('#delete_attribute_#{feeling.id}').children().first().submit()};"}= icon('fas', 'trash', 'Excluir', class: "fancy-link fancy-link--red")

            %tr{id: "feeling_#{feeling.id}_e", style: "display: none"}
              = simple_form_for(@emotion, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form" }) do |f|
                = f.simple_fields_for :feelings, feeling do |g|
                  %td= g.input :description
                  %td= f.submit "Salvar", class: "button button--green fancy-link fancy-link--white"
                  %td

            %div{id: "delete_attribute_#{feeling.id}", style: "display:none"}
              = simple_form_for(@emotion) do |f|
                = f.simple_fields_for :feelings, feeling do |g|
                  = g.input :_destroy, input_html: { value: true }

      %br
      %br

      %h3.subtitle.title--thin Adicionar Sentimento

      = simple_form_for(@emotion, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form" }) do |f|
        = f.simple_fields_for :feelings, Feeling.new do |g|
          .columns.columns--small
            .column--small.column--small--9
              = g.input :description, placeholder: "Descrição do sentimento", label: false
            .column--small.column--small--1
              = f.submit "Adicionar", class: "button button--green fancy-link fancy-link--white"