config/routes.rb
Rails.application.routes.draw do
  resources :occurrency_histories
  resources :emotions
  devise_for :readers, path: 'reader', controllers: {
    sessions: 'readers/sessions',
    registrations: 'readers/registrations',
    passwords: 'readers/passwords'
  }

  devise_for :users, path: '', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :reader do
    root to: "books#list"
    resources :guests
    resources :readers
    resources :books

    patch "/reader/update_book_comments/:id", to: "readers#update_book_comments", as: :edit_book_comment
    delete "/reader/update_book_comments/:id", to: "readers#delete_book_comments", as: :delete_book_comment
    post "/livros/add/:code", to: "readers#add_book", as: :add_book
    get "/validate_book_code", to: "readers#validate_book_code", as: :validate_book_code
  end

  authenticated :user do
    root to: "application#dashboard"

    resources :appointments do
      get :autocomplete_student_name, :on => :collection
      get :autocomplete_guest_name, :on => :collection
    end
    resources :occurrencies do
      get :autocomplete_student_name, :on => :collection
    end

    resources :appointment_evolutions
    resources :students
    resources :users
    resources :schools
    resources :phrases
    resources :guests, except: [:show]
    resources :classies
    resources :readers
    resources :books

    get "/review_occurrency/:occurrency_id", to: "application#review_occurrency", as: :review_occurrency
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "application#coming_soon"

  # Static pages of the application
  get "slides", to: "application#slides", as: :slide_show
  get "about", to: "application#about", as: :about_page
  get "soon", to: "application#soon", as: :soon

  # guests personalized routes
  post "/guests/generate_access_cards", to: "guests#generate_access_cards", as: :generate_access_cards
  get "/guests/print_access_cards", to: "guests#print_access_cards", as: :print_access_cards

  # book personalized routes
  get "/livro/:url", to: "books#read", as: :read_book
  get "/livros", to: "books#list", as: :books_list

  post "/students/:id/add_document", to: "students#add_document", as: :add_document
  post "/update_book_page_saver", to: "books#update_current_page"

  # Relatories routes
  get "/relatories", to: "relatories#index", as: :relatories
  get "/relatories/appointments", to: "relatories#appointments", as: :appointments_relatory
  get "/relatories/occurrencies", to: "relatories#occurrencies", as: :occurrencies_relatory
  get "/relatories/print_appointments/:ids", to: "relatories#print_appointments", as: :print_appointments_relatory
  get "/relatories/print_occurrencies/:ids", to: "relatories#print_occurrencies", as: :print_occurrencies_relatory
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  belongs_to :school

  # has_trash
  default_scope {where(arel_table[:deleted_at].eq(nil)) if arel_table[:deleted_at]}

  before_create :check_school, :validate_user_permission

  validates_presence_of :school, :role, required: true

  def check_school
    school = School.find(self.school.id)

    if school.user.present?
      errors.add(:base, "Essa escola já tem um usuário.")
      throw(:abort)
    end
  end

  def validate_user_permission
    if self.role == "Admin" and User.count > 0
      errors.add(:base, "Desculpe mas eu não posso permitir que isso aconteça... Este incidente será relatado.")
      throw(:abort)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout "users"

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, flash: {:success => 'Usuário criado'} }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, flash: {:warning => 'Algo deu errado, verifique os campos e tente novamente'} }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user_params = user_params

    if is_admin? and @user_params[:password].empty?
      @user_params[:password] = @user.password
      @user_params[:password_confirmation] = @user_params[:password]
    end

    respond_to do |format|
      if @user.update(@user_params)
        format.html { redirect_to users_path, flash: {:success => 'Usuário atualizado'} }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, flash: {:warning => 'Algo deu errado, verifique os campos e tente novamente'} }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, flash: {:info => 'Usuário excluído'} }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:school_id, :role, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user, defaults: { input_html: { class: "fancy-form__input" } }, html: { class: "fancy-form" }) do |f|
  %strong= f.error_notification
  %p= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  %br

  - if params[:school]
    = f.input :school_id, label: "Escola", as: :select, collection: School.all.drop(1), selected: params[:school], input_html: { class: "fancy-form__input fancy-form__select" }
  - else
    = f.input :school_id, label: "Escola", as: :select, collection: School.all.drop(1), input_html: { class: "fancy-form__input fancy-form__select" }

  = f.input :role, as: :hidden, input_html: { value: "coordenator" }
  = f.input :email
  = f.input :password, label: "Senha"
  = f.input :password_confirmation, label: "Confirme a senha"

  = f.submit "Salvar", class: "button button--green fancy-link--white"

app/views/users/edit.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Editar usuário

      %div
        = render 'form'

app/views/users/index.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Usuários

      %br

      .table
        %table.table
          %thead
            %tr
              %th{style: "width: 20px"}
              %th Escola
              %th Permissão
              %th
              %th

          %tbody
            - @users.each do |user|
              %tr
                %td
                  %div{style: "background-color: #{user.school.color}; width: 20px; height: 20px;"}
                %td= user.school.name
                %td= user.role
                %td= link_to icon('fas', 'pen', 'Editar', class: "fancy-link fancy-link--green"), edit_user_path(user), class: "fancy-link fancy-link--green" if not user == User.first
                %td= link_to icon('fas', 'trash', 'Excluir', class: "fancy-link fancy-link--red"), user, method: :delete, data: { confirm: 'Are you sure?' }, class: "fancy-link fancy-link--red" if not user == User.first

      %br

      = link_to '+ Adicionar Usuário', new_user_path, class: "fancy-link fancy-link--blue2"

app/views/users/new.html.haml
.animated.fadeIn
  .section
    .section__content
      %h1.title.title--thin.title--large Novo usuário

      %div
        = render 'form'

app/views/users/show.html.haml
.animated.fadeIn
  .section
    .section__content
      .inline
        %div{style: "background-color: #{@user.school.color}; width: 30px; height: 30px; margin-right: 20px;"}
        %h1= @user.school.name

      %p= @user.role

      = link_to 'Editar', edit_user_path(@user), class: "fancy-link"
      \|
      = link_to 'Voltar', users_path, class: "fancy-link"