config/routes.rb
Rails.application.routes.draw do
  resources :occurrency_histories
  resources :emotions
  devise_for :readers, path: 'reader', controllers: {
    sessions: 'readers/sessions',
    registrations: 'readers/registrations',
    passwords: 'readers/passwords'
  }

  devise_for :users, path: '', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  authenticated :reader do
    root to: "books#list"
    resources :guests
    resources :readers
    resources :books

    patch "/reader/update_book_comments/:id", to: "readers#update_book_comments", as: :edit_book_comment
    delete "/reader/update_book_comments/:id", to: "readers#delete_book_comments", as: :delete_book_comment
    post "/livros/add/:code", to: "readers#add_book", as: :add_book
    get "/validate_book_code", to: "readers#validate_book_code", as: :validate_book_code
  end

  authenticated :user do
    root to: "application#dashboard"

    resources :appointments do
      get :autocomplete_student_name, :on => :collection
      get :autocomplete_guest_name, :on => :collection
    end
    resources :occurrencies do
      get :autocomplete_student_name, :on => :collection
    end

    resources :appointment_evolutions
    resources :students
    resources :users
    resources :schools
    resources :phrases
    resources :guests, except: [:show]
    resources :classies
    resources :readers
    resources :books

    get "/review_occurrency/:occurrency_id", to: "application#review_occurrency", as: :review_occurrency
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # root to: "application#coming_soon"

  # Static pages of the application
  get "slides", to: "application#slides", as: :slide_show
  get "about", to: "application#about", as: :about_page
  get "soon", to: "application#soon", as: :soon

  # guests personalized routes
  post "/guests/generate_access_cards", to: "guests#generate_access_cards", as: :generate_access_cards
  get "/guests/print_access_cards", to: "guests#print_access_cards", as: :print_access_cards

  # book personalized routes
  get "/livro/:url", to: "books#read", as: :read_book
  get "/livros", to: "books#list", as: :books_list

  post "/students/:id/add_document", to: "students#add_document", as: :add_document
  post "/update_book_page_saver", to: "books#update_current_page"

  # Relatories routes
  get "/relatories", to: "relatories#index", as: :relatories
  get "/relatories/appointments", to: "relatories#appointments", as: :appointments_relatory
  get "/relatories/occurrencies", to: "relatories#occurrencies", as: :occurrencies_relatory
  get "/relatories/print_appointments/:ids", to: "relatories#print_appointments", as: :print_appointments_relatory
  get "/relatories/print_occurrencies/:ids", to: "relatories#print_occurrencies", as: :print_occurrencies_relatory
end

app/models/occurrency_history.rb
class OccurrencyHistory < ApplicationRecord
  belongs_to :occurrency
  belongs_to :student
  
  serialize :emotions, Array
end

app/helpers/occurrency_histories_helper.rb
module OccurrencyHistoriesHelper
end

app/views/occurrency_histories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@occurrency_history) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :student
    = f.association :occurrency
    = f.input :emotions

  .form-actions
    = f.button :submit

app/views/occurrency_histories/edit.html.haml
%h1 Editing occurrency_history

= render 'form'

= link_to 'Show', @occurrency_history
\|
= link_to 'Back', occurrency_histories_path

app/views/occurrency_histories/index.html.haml
%h1 Listing occurrency_histories

%table
  %thead
    %tr
      %th Student
      %th Occurrency
      %th Emotions
      %th
      %th
      %th

  %tbody
    - @occurrency_histories.each do |occurrency_history|
      %tr
        %td= occurrency_history.student
        %td= occurrency_history.occurrency
        %td= occurrency_history.emotions
        %td= link_to 'Show', occurrency_history
        %td= link_to 'Edit', edit_occurrency_history_path(occurrency_history)
        %td= link_to 'Destroy', occurrency_history, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Occurrency history', new_occurrency_history_path

app/views/occurrency_histories/new.html.haml
%h1 New occurrency_history

= render 'form'

= link_to 'Back', occurrency_histories_path

app/views/occurrency_histories/show.html.haml
%p#notice= notice

%p
  %b Student:
  = @occurrency_history.student
%p
  %b Occurrency:
  = @occurrency_history.occurrency
%p
  %b Emotions:
  = @occurrency_history.emotions

= link_to 'Edit', edit_occurrency_history_path(@occurrency_history)
\|
= link_to 'Back', occurrency_histories_path